extends:
  - "eslint:recommended"
  - "plugin:react/recommended"

parser:
  '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

env:
  browser: true
  es6: true

parserOptions:
  sourceType: module

settings:
  react:
    version: detect
