name: Test and Bundle website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Clean install dependencies
      run: npm ci

    - name: Test application
      run: npm run test

    - name: Build application
      run: npm run build

    - name: Upload built website
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: build/
        if-no-files-found: error
